-- MySQL Script generated by MySQL Workbench
-- Sun Sep  5 16:18:56 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TodoApp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TodoApp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TodoApp` DEFAULT CHARACTER SET utf8 ;
USE `TodoApp` ;

-- -----------------------------------------------------
-- Table `TodoApp`.`tb_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TodoApp`.`tb_role` (
  `id_role` INT NOT NULL,
  `name` VARCHAR(225) NULL,
  `description` VARCHAR(225) NULL,
  PRIMARY KEY (`id_role`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TodoApp`.`tb_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TodoApp`.`tb_user` (
  `id_user` INT NOT NULL,
  `full_name` VARCHAR(225) NOT NULL,
  `email` VARCHAR(225) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `forgot_password` VARCHAR(45) NULL,
  `id_role` INT NOT NULL,
  `created_at` TIMESTAMP(6) GENERATED ALWAYS AS () VIRTUAL,
  `updated_at` TIMESTAMP(6) NULL,
  PRIMARY KEY (`id_user`),
  INDEX `idx_fk_tb_user_id_role` (`id_role` ASC) VISIBLE,
  UNIQUE INDEX `idx_u_email` (`email` ASC) VISIBLE,
  CONSTRAINT `fk_tb_user_tb_role1`
    FOREIGN KEY (`id_role`)
    REFERENCES `TodoApp`.`tb_role` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TodoApp`.`tb_todo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TodoApp`.`tb_todo` (
  `id_todo` INT NOT NULL,
  `id_user` INT NOT NULL,
  `title` VARCHAR(225) NOT NULL,
  `created_at` TIMESTAMP(6) GENERATED ALWAYS AS () VIRTUAL,
  `updated_at` TIMESTAMP(6) NULL,
  PRIMARY KEY (`id_todo`),
  INDEX `idx_fk_tb_todo_id_user` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_tb_todo_tb_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `TodoApp`.`tb_user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TodoApp`.`tb_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TodoApp`.`tb_status` (
  `id_status` INT NOT NULL,
  `name` VARCHAR(225) NULL,
  PRIMARY KEY (`id_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TodoApp`.`tb_todolist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TodoApp`.`tb_todolist` (
  `id_todolist` INT NOT NULL,
  `id_todo` INT NOT NULL,
  `task` VARCHAR(225) NOT NULL,
  `id_status` INT NOT NULL DEFAULT 2,
  `created_at` TIMESTAMP(6) GENERATED ALWAYS AS (),
  `updated_at` TIMESTAMP(6) NULL,
  PRIMARY KEY (`id_todolist`),
  INDEX `idx_fk_tb_todolist_id_todo` (`id_todo` ASC) VISIBLE,
  INDEX `idx_fk_tb_todolist_id_status` (`id_status` ASC) VISIBLE,
  CONSTRAINT `fk_tb_todolist_tb_todo1`
    FOREIGN KEY (`id_todo`)
    REFERENCES `TodoApp`.`tb_todo` (`id_todo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_todolist_tb_status1`
    FOREIGN KEY (`id_status`)
    REFERENCES `TodoApp`.`tb_status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TodoApp`.`tb_attachment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TodoApp`.`tb_attachment` (
  `id_attachment` INT NOT NULL,
  `id_todolist` INT NOT NULL,
  `url` VARCHAR(225) NOT NULL,
  `caption` VARCHAR(225) NULL,
  `created_at` TIMESTAMP(6) GENERATED ALWAYS AS (),
  `updated_at` TIMESTAMP(6) NULL,
  PRIMARY KEY (`id_attachment`),
  INDEX `idx_fk_tb_attachment_id_todolist` (`id_todolist` ASC) VISIBLE,
  CONSTRAINT `fk_tb_attachment_tb_todolist1`
    FOREIGN KEY (`id_todolist`)
    REFERENCES `TodoApp`.`tb_todolist` (`id_todolist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
